server:
  port: ${PORT:8851}
eureka:
  client:
    register-with-eureka: true
    #fetch-registry: false
    serviceurl:
      defaultZone: http://localhost:8850/eureka/
#  instance:
#    instance:
#      id: ${spring.application.name}:${random.uuid}
message: Configuracion de Api gateway en el servidor levantado!
spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes[0]: 
        id: customer-microservice
        uri: lb://MS_CAJERO
        predicates[0]: Path=/apimscustomer/**
        
        
        



