server:
  port: ${PORT:8851}
eureka:
  client:
    register-with-eureka: true
    #fetch-registry: false
    serviceurl:
      defaultZone: http://localhost:8850/eureka/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: cajero-service
        uri: http://localhost:8863/
        predicates:
        - Path=/apicajero/**
message: Configuracion de Api gateway en el servidor levantado!
